language: python

matrix:
  allow_failures:
    - env: ARTISAN_OS=rpi
  include:
  - os: linux
    python: 3.7
    sudo: required
    cache:
      - pip
      - bundler
    env:
      - ARTISAN_OS=linux
  - os: linux
    language: generic
    sudo: required
    env:
      ARTISAN_OS=rpi
  - os: osx
    python: 3.6
    language: generic
    cache:
      - pip
    env:
      - ARTISAN_OS=osx

install:
  - export GIT_VERSION=`git rev-parse --verify --short HEAD 2>/dev/null|| echo "???"`
  - sed -i'' -e "s/__revision__ = '0'/__revision__ = '$GIT_VERSION'/" src/artisanlib/__init__.py
  - .travis/install-${ARTISAN_OS}.sh
  
before_script:
  - ulimit -c unlimited -S

after_failure:
  - find .  -name "core*"
  - file src/core
  - gdb -c src/core `which python3` -ex "thread apply all bt" -ex "set pagination 0" -batch

script:
  - .travis/script-${ARTISAN_OS}.sh

deploy:
  skip_cleanup: true
  provider: bintray
  file: ".bintray.json"
  user: rpaulo
  key:
    secure: "I2HeXkPR3Dd3FD0dKv+zM3cSyk5fvn8W2F8i75uBfrnTx5Ph6HCn0DGeXMtPS/PPj9ZRAxdWZqh0TUTDD/iQFABInqMP2vdS96F/A9wCd9SLuiBuGFinwiLCUoLUeIkOrS3dBCIujAJJ2FLBNHdXBKxFbqaphtnFBawMnPM4rmdOGSGIb8A17bBFGOf0WBe5FQc1hPWgoe7Lz3sTDHwvGSlcFS9qCwaR0VqxqvKDUdp3bsybMAJmFKK1LMmj3m5lZXXS2KpnHNgywfVZk1rjKqGLI/C0XAccpMWvNwZDFQmy2NsFumxmqHuIQVyxL1h4swMMBO2L5Chfj5xmMKf7LC4l5/rl6PhsEIgul+tDAisztlhjuMFX3/zR36KouAqD4qsyhvBUnNKxbsHVLCdyTlOA0qNJqbTPb955jDUFlH110RzHEP3VLBHHnyZNsgtKxVSpU4fbA2E1cFTokhwhhbyFoXZ+5sGNVBoi2H2yWjid/Ylw8TMMo8DISsZCZPztYrjO/zjv2k8L7O9txqb4Enxl1z1wpi9f5icZDasg/NF3cvGAZoMx+5at6lvsLhR1FmwXyonPO2jFeMC7ReU9TWApSzrM1pq+SOePXXIrMrVP0P5zwC6lj/UehAwHnb1Z+LY7BBk9DgZLj8pGhXtZuEKYDmUu6a56204PkuYeXiM="
  on:
    branch: master
    
 

